esphome:
  name: esp32display
  platform: ESP32
  board: lolin_d32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.178.101
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.178.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
    dns1: 192.168.178.2

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

esp32_ble_tracker:
  scan_interval: 30s

time:
  - platform: homeassistant
    timezone: Australia/Melbourne
    id: homeassistant_time

web_server:
  port: 80

font:
  - file: OpenSans-Regular.ttf
    id: font
    size: 10
  
i2c:
  sda: 5
  scl: 4

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x32"
    address: 0x3C
    update_interval:
      seconds: 1
    lambda: |-
      it.strftime(0, 0, id(font), "%a %b%e  %I:%M %p", id(homeassistant_time).now());
      it.printf(0, 15, id(font), "T: %s°C", id(home_temperature).state.c_str());
      it.printf(0, 23, id(font), "H: %s%%", id(home_humidity).state.c_str());
      
sensor:
  - platform: wifi_signal
    name: esp32display_wifi
    update_interval: 60s
  - platform: uptime
    name: esp32display_uptime

text_sensor:
  - platform: homeassistant
    name: "House Temperature From Home Assistant"
    entity_id: sensor.d1minirelay1_temperature
    id: home_temperature
    internal: True
  - platform: homeassistant
    name: "House Humidity From Home Assistant"
    entity_id: sensor.d1minirelay1_humidity
    internal: True
    id: home_humidity