esphome:
  name: sonoffswitch4
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.178.102
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.178.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
    dns1: 192.168.178.2
    
api:

logger:

ota:

web_server:
  port: 80

sensor:
  - platform: wifi_signal
    name: sonoffswitch4_wifi
    update_interval: 60s
  - platform: uptime
    name: sonoffswitch4_uptime

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff Basic Button"
    on_press:
      then:
        - switch.toggle: relay
#        - light.toggle: status_light

switch:
  - platform: gpio
    name: "Sonoff Basic Relay"
    pin: GPIO12
    id: relay
    on_turn_on:
      then:
        - output.turn_on: basic_green_led
    on_turn_off:
      then:
        - output.turn_off: basic_green_led

output:
  - platform: esp8266_pwm
    id: basic_green_led
    pin:
      number: GPIO13
      inverted: True



